---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: juicypie-backend-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: backend.juicypie.smarter.codes
    http:
      paths:
      - path: /
        backend:
          serviceName: juicypie-backend-service
          servicePort: 9200
